name: locale_emoji
description: "Convert ðŸŒ Locale (language code, script code and country code) to the corresponding ðŸ³ï¸ Emoji Flag ðŸ´"
version: 0.2.1
homepage: https://github.com/MichaelDark/locale_emoji

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  http: ^0.13.0
