name: locale_emoji_flutter
description: "Convert ğŸŒ Locale (language code, script code and country code) to the corresponding ğŸ³ï¸ Emoji Flag ğŸ´"
version: 0.2.1
homepage: https://github.com/MichaelDark/locale_emoji

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  locale_emoji: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
